//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Free1X2.EntradaSalida.GenerarCPs {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class ColumnasProbables : DataSet {
        
        private Tipos_de_CPsDataTable tableTipos_de_CPs;
        
        private Configuracion_de_CPsDataTable tableConfiguracion_de_CPs;
        
        private DataRelation relationConfiguración;
        
        public ColumnasProbables() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected ColumnasProbables(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Tipos de CPs"] != null)) {
                    this.Tables.Add(new Tipos_de_CPsDataTable(ds.Tables["Tipos de CPs"]));
                }
                if ((ds.Tables["Configuracion de CPs"] != null)) {
                    this.Tables.Add(new Configuracion_de_CPsDataTable(ds.Tables["Configuracion de CPs"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public Tipos_de_CPsDataTable Tipos_de_CPs {
            get {
                return this.tableTipos_de_CPs;
            }
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public Configuracion_de_CPsDataTable Configuracion_de_CPs {
            get {
                return this.tableConfiguracion_de_CPs;
            }
        }
        
        public override DataSet Clone() {
            ColumnasProbables cln = ((ColumnasProbables)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Tipos de CPs"] != null)) {
                this.Tables.Add(new Tipos_de_CPsDataTable(ds.Tables["Tipos de CPs"]));
            }
            if ((ds.Tables["Configuracion de CPs"] != null)) {
                this.Tables.Add(new Configuracion_de_CPsDataTable(ds.Tables["Configuracion de CPs"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableTipos_de_CPs = ((Tipos_de_CPsDataTable)(this.Tables["Tipos de CPs"]));
            if ((this.tableTipos_de_CPs != null)) {
                this.tableTipos_de_CPs.InitVars();
            }
            this.tableConfiguracion_de_CPs = ((Configuracion_de_CPsDataTable)(this.Tables["Configuracion de CPs"]));
            if ((this.tableConfiguracion_de_CPs != null)) {
                this.tableConfiguracion_de_CPs.InitVars();
            }
            this.relationConfiguración = this.Relations["Configuración"];
        }
        
        private void InitClass() {
            this.DataSetName = "ColumnasProbables";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/ColumnasProbables.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableTipos_de_CPs = new Tipos_de_CPsDataTable();
            this.Tables.Add(this.tableTipos_de_CPs);
            this.tableConfiguracion_de_CPs = new Configuracion_de_CPsDataTable();
            this.Tables.Add(this.tableConfiguracion_de_CPs);
            ForeignKeyConstraint fkc;
            fkc = new ForeignKeyConstraint("Configuración", new DataColumn[] {
                        this.tableTipos_de_CPs.TipoColumn}, new DataColumn[] {
                        this.tableConfiguracion_de_CPs.TipoColumn});
            this.tableConfiguracion_de_CPs.Constraints.Add(fkc);
            fkc.AcceptRejectRule = AcceptRejectRule.None;
            fkc.DeleteRule = Rule.Cascade;
            fkc.UpdateRule = Rule.Cascade;
            this.relationConfiguración = new DataRelation("Configuración", new DataColumn[] {
                        this.tableTipos_de_CPs.TipoColumn}, new DataColumn[] {
                        this.tableConfiguracion_de_CPs.TipoColumn}, false);
            this.Relations.Add(this.relationConfiguración);
        }
        
        private bool ShouldSerializeTipos_de_CPs() {
            return false;
        }
        
        private bool ShouldSerializeConfiguracion_de_CPs() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void Tipos_de_CPsRowChangeEventHandler(object sender, Tipos_de_CPsRowChangeEvent e);
        
        public delegate void Configuracion_de_CPsRowChangeEventHandler(object sender, Configuracion_de_CPsRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class Tipos_de_CPsDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnTipo;
            
            private DataColumn columnNombre;
            
            internal Tipos_de_CPsDataTable() : 
                    base("Tipos de CPs") {
                this.InitClass();
            }
            
            internal Tipos_de_CPsDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn TipoColumn {
                get {
                    return this.columnTipo;
                }
            }
            
            internal DataColumn NombreColumn {
                get {
                    return this.columnNombre;
                }
            }
            
            public Tipos_de_CPsRow this[int index] {
                get {
                    return ((Tipos_de_CPsRow)(this.Rows[index]));
                }
            }
            
            public event Tipos_de_CPsRowChangeEventHandler Tipos_de_CPsRowChanged;
            
            public event Tipos_de_CPsRowChangeEventHandler Tipos_de_CPsRowChanging;
            
            public event Tipos_de_CPsRowChangeEventHandler Tipos_de_CPsRowDeleted;
            
            public event Tipos_de_CPsRowChangeEventHandler Tipos_de_CPsRowDeleting;
            
            public void AddTipos_de_CPsRow(Tipos_de_CPsRow row) {
                this.Rows.Add(row);
            }
            
            public Tipos_de_CPsRow AddTipos_de_CPsRow(int Tipo, string Nombre) {
                Tipos_de_CPsRow rowTipos_de_CPsRow = ((Tipos_de_CPsRow)(this.NewRow()));
                rowTipos_de_CPsRow.ItemArray = new object[] {
                        Tipo,
                        Nombre};
                this.Rows.Add(rowTipos_de_CPsRow);
                return rowTipos_de_CPsRow;
            }
            
            public Tipos_de_CPsRow FindByTipo(int Tipo) {
                return ((Tipos_de_CPsRow)(this.Rows.Find(new object[] {
                            Tipo})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                Tipos_de_CPsDataTable cln = ((Tipos_de_CPsDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new Tipos_de_CPsDataTable();
            }
            
            internal void InitVars() {
                this.columnTipo = this.Columns["Tipo"];
                this.columnNombre = this.Columns["Nombre"];
            }
            
            private void InitClass() {
                this.columnTipo = new DataColumn("Tipo", typeof(int), null, System.Data.MappingType.Attribute);
                this.Columns.Add(this.columnTipo);
                this.columnNombre = new DataColumn("Nombre", typeof(string), null, System.Data.MappingType.Attribute);
                this.Columns.Add(this.columnNombre);
                this.Constraints.Add(new UniqueConstraint("ColumnasProbablesKey3", new DataColumn[] {
                                this.columnTipo}, true));
                this.columnTipo.AllowDBNull = false;
                this.columnTipo.Unique = true;
                this.columnTipo.Namespace = "http://tempuri.org/ColumnasProbables.xsd";
                this.columnNombre.Namespace = "http://tempuri.org/ColumnasProbables.xsd";
            }
            
            public Tipos_de_CPsRow NewTipos_de_CPsRow() {
                return ((Tipos_de_CPsRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new Tipos_de_CPsRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(Tipos_de_CPsRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.Tipos_de_CPsRowChanged != null)) {
                    this.Tipos_de_CPsRowChanged(this, new Tipos_de_CPsRowChangeEvent(((Tipos_de_CPsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.Tipos_de_CPsRowChanging != null)) {
                    this.Tipos_de_CPsRowChanging(this, new Tipos_de_CPsRowChangeEvent(((Tipos_de_CPsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.Tipos_de_CPsRowDeleted != null)) {
                    this.Tipos_de_CPsRowDeleted(this, new Tipos_de_CPsRowChangeEvent(((Tipos_de_CPsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.Tipos_de_CPsRowDeleting != null)) {
                    this.Tipos_de_CPsRowDeleting(this, new Tipos_de_CPsRowChangeEvent(((Tipos_de_CPsRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveTipos_de_CPsRow(Tipos_de_CPsRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class Tipos_de_CPsRow : DataRow {
            
            private Tipos_de_CPsDataTable tableTipos_de_CPs;
            
            internal Tipos_de_CPsRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableTipos_de_CPs = ((Tipos_de_CPsDataTable)(this.Table));
            }
            
            public int Tipo {
                get {
                    return ((int)(this[this.tableTipos_de_CPs.TipoColumn]));
                }
                set {
                    this[this.tableTipos_de_CPs.TipoColumn] = value;
                }
            }
            
            public string Nombre {
                get {
                    try {
                        return ((string)(this[this.tableTipos_de_CPs.NombreColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tableTipos_de_CPs.NombreColumn] = value;
                }
            }
            
            public bool IsNombreNull() {
                return this.IsNull(this.tableTipos_de_CPs.NombreColumn);
            }
            
            public void SetNombreNull() {
                this[this.tableTipos_de_CPs.NombreColumn] = System.Convert.DBNull;
            }
            
            public Configuracion_de_CPsRow[] GetConfiguracion_de_CPsRows() {
                return ((Configuracion_de_CPsRow[])(this.GetChildRows(this.Table.ChildRelations["Configuración"])));
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class Tipos_de_CPsRowChangeEvent : EventArgs {
            
            private Tipos_de_CPsRow eventRow;
            
            private DataRowAction eventAction;
            
            public Tipos_de_CPsRowChangeEvent(Tipos_de_CPsRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public Tipos_de_CPsRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class Configuracion_de_CPsDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnTipo;
            
            private DataColumn columnDesde;
            
            private DataColumn columnHasta;
            
            private DataColumn columnForzar_Fijos;
            
            private DataColumn columnNum_Fijos;
            
            private DataColumn columnForzar_Dobles;
            
            private DataColumn columnNum_Dobles;
            
            private DataColumn columnForzar_Triples;
            
            internal Configuracion_de_CPsDataTable() : 
                    base("Configuracion de CPs") {
                this.InitClass();
            }
            
            internal Configuracion_de_CPsDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn TipoColumn {
                get {
                    return this.columnTipo;
                }
            }
            
            internal DataColumn DesdeColumn {
                get {
                    return this.columnDesde;
                }
            }
            
            internal DataColumn HastaColumn {
                get {
                    return this.columnHasta;
                }
            }
            
            internal DataColumn Forzar_FijosColumn {
                get {
                    return this.columnForzar_Fijos;
                }
            }
            
            internal DataColumn Num_FijosColumn {
                get {
                    return this.columnNum_Fijos;
                }
            }
            
            internal DataColumn Forzar_DoblesColumn {
                get {
                    return this.columnForzar_Dobles;
                }
            }
            
            internal DataColumn Num_DoblesColumn {
                get {
                    return this.columnNum_Dobles;
                }
            }
            
            internal DataColumn Forzar_TriplesColumn {
                get {
                    return this.columnForzar_Triples;
                }
            }
            
            public Configuracion_de_CPsRow this[int index] {
                get {
                    return ((Configuracion_de_CPsRow)(this.Rows[index]));
                }
            }
            
            public event Configuracion_de_CPsRowChangeEventHandler Configuracion_de_CPsRowChanged;
            
            public event Configuracion_de_CPsRowChangeEventHandler Configuracion_de_CPsRowChanging;
            
            public event Configuracion_de_CPsRowChangeEventHandler Configuracion_de_CPsRowDeleted;
            
            public event Configuracion_de_CPsRowChangeEventHandler Configuracion_de_CPsRowDeleting;
            
            public void AddConfiguracion_de_CPsRow(Configuracion_de_CPsRow row) {
                this.Rows.Add(row);
            }
            
            public Configuracion_de_CPsRow AddConfiguracion_de_CPsRow(Tipos_de_CPsRow parentTipos_de_CPsRowByConfiguración, int Desde, int Hasta, bool Forzar_Fijos, int Num_Fijos, bool Forzar_Dobles, int Num_Dobles, bool Forzar_Triples) {
                Configuracion_de_CPsRow rowConfiguracion_de_CPsRow = ((Configuracion_de_CPsRow)(this.NewRow()));
                rowConfiguracion_de_CPsRow.ItemArray = new object[] {
                        parentTipos_de_CPsRowByConfiguración[0],
                        Desde,
                        Hasta,
                        Forzar_Fijos,
                        Num_Fijos,
                        Forzar_Dobles,
                        Num_Dobles,
                        Forzar_Triples};
                this.Rows.Add(rowConfiguracion_de_CPsRow);
                return rowConfiguracion_de_CPsRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                Configuracion_de_CPsDataTable cln = ((Configuracion_de_CPsDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new Configuracion_de_CPsDataTable();
            }
            
            internal void InitVars() {
                this.columnTipo = this.Columns["Tipo"];
                this.columnDesde = this.Columns["Desde"];
                this.columnHasta = this.Columns["Hasta"];
                this.columnForzar_Fijos = this.Columns["Forzar Fijos"];
                this.columnNum_Fijos = this.Columns["Num Fijos"];
                this.columnForzar_Dobles = this.Columns["Forzar Dobles"];
                this.columnNum_Dobles = this.Columns["Num Dobles"];
                this.columnForzar_Triples = this.Columns["Forzar Triples"];
            }
            
            private void InitClass() {
                this.columnTipo = new DataColumn("Tipo", typeof(int), null, System.Data.MappingType.Attribute);
                this.Columns.Add(this.columnTipo);
                this.columnDesde = new DataColumn("Desde", typeof(int), null, System.Data.MappingType.Attribute);
                this.Columns.Add(this.columnDesde);
                this.columnHasta = new DataColumn("Hasta", typeof(int), null, System.Data.MappingType.Attribute);
                this.Columns.Add(this.columnHasta);
                this.columnForzar_Fijos = new DataColumn("Forzar Fijos", typeof(bool), null, System.Data.MappingType.Attribute);
                this.Columns.Add(this.columnForzar_Fijos);
                this.columnNum_Fijos = new DataColumn("Num Fijos", typeof(int), null, System.Data.MappingType.Attribute);
                this.Columns.Add(this.columnNum_Fijos);
                this.columnForzar_Dobles = new DataColumn("Forzar Dobles", typeof(bool), null, System.Data.MappingType.Attribute);
                this.Columns.Add(this.columnForzar_Dobles);
                this.columnNum_Dobles = new DataColumn("Num Dobles", typeof(int), null, System.Data.MappingType.Attribute);
                this.Columns.Add(this.columnNum_Dobles);
                this.columnForzar_Triples = new DataColumn("Forzar Triples", typeof(bool), null, System.Data.MappingType.Attribute);
                this.Columns.Add(this.columnForzar_Triples);
                this.columnTipo.Namespace = "http://tempuri.org/ColumnasProbables.xsd";
                this.columnDesde.Namespace = "http://tempuri.org/ColumnasProbables.xsd";
                this.columnHasta.Namespace = "http://tempuri.org/ColumnasProbables.xsd";
                this.columnForzar_Fijos.Namespace = "http://tempuri.org/ColumnasProbables.xsd";
                this.columnNum_Fijos.Namespace = "http://tempuri.org/ColumnasProbables.xsd";
                this.columnForzar_Dobles.Namespace = "http://tempuri.org/ColumnasProbables.xsd";
                this.columnNum_Dobles.Namespace = "http://tempuri.org/ColumnasProbables.xsd";
                this.columnForzar_Triples.Namespace = "http://tempuri.org/ColumnasProbables.xsd";
            }
            
            public Configuracion_de_CPsRow NewConfiguracion_de_CPsRow() {
                return ((Configuracion_de_CPsRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new Configuracion_de_CPsRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(Configuracion_de_CPsRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.Configuracion_de_CPsRowChanged != null)) {
                    this.Configuracion_de_CPsRowChanged(this, new Configuracion_de_CPsRowChangeEvent(((Configuracion_de_CPsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.Configuracion_de_CPsRowChanging != null)) {
                    this.Configuracion_de_CPsRowChanging(this, new Configuracion_de_CPsRowChangeEvent(((Configuracion_de_CPsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.Configuracion_de_CPsRowDeleted != null)) {
                    this.Configuracion_de_CPsRowDeleted(this, new Configuracion_de_CPsRowChangeEvent(((Configuracion_de_CPsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.Configuracion_de_CPsRowDeleting != null)) {
                    this.Configuracion_de_CPsRowDeleting(this, new Configuracion_de_CPsRowChangeEvent(((Configuracion_de_CPsRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveConfiguracion_de_CPsRow(Configuracion_de_CPsRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class Configuracion_de_CPsRow : DataRow {
            
            private Configuracion_de_CPsDataTable tableConfiguracion_de_CPs;
            
            internal Configuracion_de_CPsRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableConfiguracion_de_CPs = ((Configuracion_de_CPsDataTable)(this.Table));
            }
            
            public int Tipo {
                get {
                    try {
                        return ((int)(this[this.tableConfiguracion_de_CPs.TipoColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tableConfiguracion_de_CPs.TipoColumn] = value;
                }
            }
            
            public int Desde {
                get {
                    try {
                        return ((int)(this[this.tableConfiguracion_de_CPs.DesdeColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tableConfiguracion_de_CPs.DesdeColumn] = value;
                }
            }
            
            public int Hasta {
                get {
                    try {
                        return ((int)(this[this.tableConfiguracion_de_CPs.HastaColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tableConfiguracion_de_CPs.HastaColumn] = value;
                }
            }
            
            public bool Forzar_Fijos {
                get {
                    try {
                        return ((bool)(this[this.tableConfiguracion_de_CPs.Forzar_FijosColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tableConfiguracion_de_CPs.Forzar_FijosColumn] = value;
                }
            }
            
            public int Num_Fijos {
                get {
                    try {
                        return ((int)(this[this.tableConfiguracion_de_CPs.Num_FijosColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tableConfiguracion_de_CPs.Num_FijosColumn] = value;
                }
            }
            
            public bool Forzar_Dobles {
                get {
                    try {
                        return ((bool)(this[this.tableConfiguracion_de_CPs.Forzar_DoblesColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tableConfiguracion_de_CPs.Forzar_DoblesColumn] = value;
                }
            }
            
            public int Num_Dobles {
                get {
                    try {
                        return ((int)(this[this.tableConfiguracion_de_CPs.Num_DoblesColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tableConfiguracion_de_CPs.Num_DoblesColumn] = value;
                }
            }
            
            public bool Forzar_Triples {
                get {
                    try {
                        return ((bool)(this[this.tableConfiguracion_de_CPs.Forzar_TriplesColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.tableConfiguracion_de_CPs.Forzar_TriplesColumn] = value;
                }
            }
            
            public Tipos_de_CPsRow Tipos_de_CPsRow {
                get {
                    return ((Tipos_de_CPsRow)(this.GetParentRow(this.Table.ParentRelations["Configuración"])));
                }
                set {
                    this.SetParentRow(value, this.Table.ParentRelations["Configuración"]);
                }
            }
            
            public bool IsTipoNull() {
                return this.IsNull(this.tableConfiguracion_de_CPs.TipoColumn);
            }
            
            public void SetTipoNull() {
                this[this.tableConfiguracion_de_CPs.TipoColumn] = System.Convert.DBNull;
            }
            
            public bool IsDesdeNull() {
                return this.IsNull(this.tableConfiguracion_de_CPs.DesdeColumn);
            }
            
            public void SetDesdeNull() {
                this[this.tableConfiguracion_de_CPs.DesdeColumn] = System.Convert.DBNull;
            }
            
            public bool IsHastaNull() {
                return this.IsNull(this.tableConfiguracion_de_CPs.HastaColumn);
            }
            
            public void SetHastaNull() {
                this[this.tableConfiguracion_de_CPs.HastaColumn] = System.Convert.DBNull;
            }
            
            public bool IsForzar_FijosNull() {
                return this.IsNull(this.tableConfiguracion_de_CPs.Forzar_FijosColumn);
            }
            
            public void SetForzar_FijosNull() {
                this[this.tableConfiguracion_de_CPs.Forzar_FijosColumn] = System.Convert.DBNull;
            }
            
            public bool IsNum_FijosNull() {
                return this.IsNull(this.tableConfiguracion_de_CPs.Num_FijosColumn);
            }
            
            public void SetNum_FijosNull() {
                this[this.tableConfiguracion_de_CPs.Num_FijosColumn] = System.Convert.DBNull;
            }
            
            public bool IsForzar_DoblesNull() {
                return this.IsNull(this.tableConfiguracion_de_CPs.Forzar_DoblesColumn);
            }
            
            public void SetForzar_DoblesNull() {
                this[this.tableConfiguracion_de_CPs.Forzar_DoblesColumn] = System.Convert.DBNull;
            }
            
            public bool IsNum_DoblesNull() {
                return this.IsNull(this.tableConfiguracion_de_CPs.Num_DoblesColumn);
            }
            
            public void SetNum_DoblesNull() {
                this[this.tableConfiguracion_de_CPs.Num_DoblesColumn] = System.Convert.DBNull;
            }
            
            public bool IsForzar_TriplesNull() {
                return this.IsNull(this.tableConfiguracion_de_CPs.Forzar_TriplesColumn);
            }
            
            public void SetForzar_TriplesNull() {
                this[this.tableConfiguracion_de_CPs.Forzar_TriplesColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class Configuracion_de_CPsRowChangeEvent : EventArgs {
            
            private Configuracion_de_CPsRow eventRow;
            
            private DataRowAction eventAction;
            
            public Configuracion_de_CPsRowChangeEvent(Configuracion_de_CPsRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public Configuracion_de_CPsRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
