//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace Free1X2.SVC_Actualizador {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Free1X2WServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Free1X2WService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UltimaVersionFree1X2OperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerBoletoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlmacenarInformeErrorOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerJornadaActualOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerNotificacionesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Free1X2WService() {
            this.Url = global::Free1X2.Properties.Settings.Default.Free1X2_SVC_Actualizador_Free1X2WService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UltimaVersionFree1X2CompletedEventHandler UltimaVersionFree1X2Completed;
        
        /// <remarks/>
        public event ObtenerBoletoCompletedEventHandler ObtenerBoletoCompleted;
        
        /// <remarks/>
        public event AlmacenarInformeErrorCompletedEventHandler AlmacenarInformeErrorCompleted;
        
        /// <remarks/>
        public event ObtenerJornadaActualCompletedEventHandler ObtenerJornadaActualCompleted;
        
        /// <remarks/>
        public event ObtenerNotificacionesCompletedEventHandler ObtenerNotificacionesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UltimaVersionFree1X2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UltimaVersionFree1X2() {
            object[] results = this.Invoke("UltimaVersionFree1X2", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UltimaVersionFree1X2Async() {
            this.UltimaVersionFree1X2Async(null);
        }
        
        /// <remarks/>
        public void UltimaVersionFree1X2Async(object userState) {
            if ((this.UltimaVersionFree1X2OperationCompleted == null)) {
                this.UltimaVersionFree1X2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnUltimaVersionFree1X2OperationCompleted);
            }
            this.InvokeAsync("UltimaVersionFree1X2", new object[0], this.UltimaVersionFree1X2OperationCompleted, userState);
        }
        
        private void OnUltimaVersionFree1X2OperationCompleted(object arg) {
            if ((this.UltimaVersionFree1X2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UltimaVersionFree1X2Completed(this, new UltimaVersionFree1X2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerBoleto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerBoleto(int jornada, string temporada) {
            object[] results = this.Invoke("ObtenerBoleto", new object[] {
                        jornada,
                        temporada});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerBoletoAsync(int jornada, string temporada) {
            this.ObtenerBoletoAsync(jornada, temporada, null);
        }
        
        /// <remarks/>
        public void ObtenerBoletoAsync(int jornada, string temporada, object userState) {
            if ((this.ObtenerBoletoOperationCompleted == null)) {
                this.ObtenerBoletoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerBoletoOperationCompleted);
            }
            this.InvokeAsync("ObtenerBoleto", new object[] {
                        jornada,
                        temporada}, this.ObtenerBoletoOperationCompleted, userState);
        }
        
        private void OnObtenerBoletoOperationCompleted(object arg) {
            if ((this.ObtenerBoletoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerBoletoCompleted(this, new ObtenerBoletoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AlmacenarInformeError", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlmacenarInformeError(string texto, string objeto, string infoAdicional, string version, string user, string email) {
            this.Invoke("AlmacenarInformeError", new object[] {
                        texto,
                        objeto,
                        infoAdicional,
                        version,
                        user,
                        email});
        }
        
        /// <remarks/>
        public void AlmacenarInformeErrorAsync(string texto, string objeto, string infoAdicional, string version, string user, string email) {
            this.AlmacenarInformeErrorAsync(texto, objeto, infoAdicional, version, user, email, null);
        }
        
        /// <remarks/>
        public void AlmacenarInformeErrorAsync(string texto, string objeto, string infoAdicional, string version, string user, string email, object userState) {
            if ((this.AlmacenarInformeErrorOperationCompleted == null)) {
                this.AlmacenarInformeErrorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlmacenarInformeErrorOperationCompleted);
            }
            this.InvokeAsync("AlmacenarInformeError", new object[] {
                        texto,
                        objeto,
                        infoAdicional,
                        version,
                        user,
                        email}, this.AlmacenarInformeErrorOperationCompleted, userState);
        }
        
        private void OnAlmacenarInformeErrorOperationCompleted(object arg) {
            if ((this.AlmacenarInformeErrorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlmacenarInformeErrorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerJornadaActual", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public JornadaActual ObtenerJornadaActual() {
            object[] results = this.Invoke("ObtenerJornadaActual", new object[0]);
            return ((JornadaActual)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerJornadaActualAsync() {
            this.ObtenerJornadaActualAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerJornadaActualAsync(object userState) {
            if ((this.ObtenerJornadaActualOperationCompleted == null)) {
                this.ObtenerJornadaActualOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerJornadaActualOperationCompleted);
            }
            this.InvokeAsync("ObtenerJornadaActual", new object[0], this.ObtenerJornadaActualOperationCompleted, userState);
        }
        
        private void OnObtenerJornadaActualOperationCompleted(object arg) {
            if ((this.ObtenerJornadaActualCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerJornadaActualCompleted(this, new ObtenerJornadaActualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerNotificaciones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public NotificacionFree1x2[] ObtenerNotificaciones(System.DateTime fechaUltimaComprobacion) {
            object[] results = this.Invoke("ObtenerNotificaciones", new object[] {
                        fechaUltimaComprobacion});
            return ((NotificacionFree1x2[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerNotificacionesAsync(System.DateTime fechaUltimaComprobacion) {
            this.ObtenerNotificacionesAsync(fechaUltimaComprobacion, null);
        }
        
        /// <remarks/>
        public void ObtenerNotificacionesAsync(System.DateTime fechaUltimaComprobacion, object userState) {
            if ((this.ObtenerNotificacionesOperationCompleted == null)) {
                this.ObtenerNotificacionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerNotificacionesOperationCompleted);
            }
            this.InvokeAsync("ObtenerNotificaciones", new object[] {
                        fechaUltimaComprobacion}, this.ObtenerNotificacionesOperationCompleted, userState);
        }
        
        private void OnObtenerNotificacionesOperationCompleted(object arg) {
            if ((this.ObtenerNotificacionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerNotificacionesCompleted(this, new ObtenerNotificacionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class JornadaActual {
        
        private bool jornadaActivaField;
        
        private string p1Field;
        
        private string p2Field;
        
        private string p3Field;
        
        private string p4Field;
        
        private string p5Field;
        
        private string p6Field;
        
        private string p7Field;
        
        private string p8Field;
        
        private string p9Field;
        
        private string p10Field;
        
        private string p11Field;
        
        private string p12Field;
        
        private string p13Field;
        
        private string p14Field;
        
        private string p15Field;
        
        private string equiposPartido1Field;
        
        private string equiposPartido2Field;
        
        private string equiposPartido3Field;
        
        private string equiposPartido4Field;
        
        private string equiposPartido5Field;
        
        private string equiposPartido6Field;
        
        private string equiposPartido7Field;
        
        private string equiposPartido8Field;
        
        private string equiposPartido9Field;
        
        private string equiposPartido10Field;
        
        private string equiposPartido11Field;
        
        private string equiposPartido12Field;
        
        private string equiposPartido13Field;
        
        private string equiposPartido14Field;
        
        private string equiposPartido15Field;
        
        /// <remarks/>
        public bool JornadaActiva {
            get {
                return this.jornadaActivaField;
            }
            set {
                this.jornadaActivaField = value;
            }
        }
        
        /// <remarks/>
        public string P1 {
            get {
                return this.p1Field;
            }
            set {
                this.p1Field = value;
            }
        }
        
        /// <remarks/>
        public string P2 {
            get {
                return this.p2Field;
            }
            set {
                this.p2Field = value;
            }
        }
        
        /// <remarks/>
        public string P3 {
            get {
                return this.p3Field;
            }
            set {
                this.p3Field = value;
            }
        }
        
        /// <remarks/>
        public string P4 {
            get {
                return this.p4Field;
            }
            set {
                this.p4Field = value;
            }
        }
        
        /// <remarks/>
        public string P5 {
            get {
                return this.p5Field;
            }
            set {
                this.p5Field = value;
            }
        }
        
        /// <remarks/>
        public string P6 {
            get {
                return this.p6Field;
            }
            set {
                this.p6Field = value;
            }
        }
        
        /// <remarks/>
        public string P7 {
            get {
                return this.p7Field;
            }
            set {
                this.p7Field = value;
            }
        }
        
        /// <remarks/>
        public string P8 {
            get {
                return this.p8Field;
            }
            set {
                this.p8Field = value;
            }
        }
        
        /// <remarks/>
        public string P9 {
            get {
                return this.p9Field;
            }
            set {
                this.p9Field = value;
            }
        }
        
        /// <remarks/>
        public string P10 {
            get {
                return this.p10Field;
            }
            set {
                this.p10Field = value;
            }
        }
        
        /// <remarks/>
        public string P11 {
            get {
                return this.p11Field;
            }
            set {
                this.p11Field = value;
            }
        }
        
        /// <remarks/>
        public string P12 {
            get {
                return this.p12Field;
            }
            set {
                this.p12Field = value;
            }
        }
        
        /// <remarks/>
        public string P13 {
            get {
                return this.p13Field;
            }
            set {
                this.p13Field = value;
            }
        }
        
        /// <remarks/>
        public string P14 {
            get {
                return this.p14Field;
            }
            set {
                this.p14Field = value;
            }
        }
        
        /// <remarks/>
        public string P15 {
            get {
                return this.p15Field;
            }
            set {
                this.p15Field = value;
            }
        }
        
        /// <remarks/>
        public string EquiposPartido1 {
            get {
                return this.equiposPartido1Field;
            }
            set {
                this.equiposPartido1Field = value;
            }
        }
        
        /// <remarks/>
        public string EquiposPartido2 {
            get {
                return this.equiposPartido2Field;
            }
            set {
                this.equiposPartido2Field = value;
            }
        }
        
        /// <remarks/>
        public string EquiposPartido3 {
            get {
                return this.equiposPartido3Field;
            }
            set {
                this.equiposPartido3Field = value;
            }
        }
        
        /// <remarks/>
        public string EquiposPartido4 {
            get {
                return this.equiposPartido4Field;
            }
            set {
                this.equiposPartido4Field = value;
            }
        }
        
        /// <remarks/>
        public string EquiposPartido5 {
            get {
                return this.equiposPartido5Field;
            }
            set {
                this.equiposPartido5Field = value;
            }
        }
        
        /// <remarks/>
        public string EquiposPartido6 {
            get {
                return this.equiposPartido6Field;
            }
            set {
                this.equiposPartido6Field = value;
            }
        }
        
        /// <remarks/>
        public string EquiposPartido7 {
            get {
                return this.equiposPartido7Field;
            }
            set {
                this.equiposPartido7Field = value;
            }
        }
        
        /// <remarks/>
        public string EquiposPartido8 {
            get {
                return this.equiposPartido8Field;
            }
            set {
                this.equiposPartido8Field = value;
            }
        }
        
        /// <remarks/>
        public string EquiposPartido9 {
            get {
                return this.equiposPartido9Field;
            }
            set {
                this.equiposPartido9Field = value;
            }
        }
        
        /// <remarks/>
        public string EquiposPartido10 {
            get {
                return this.equiposPartido10Field;
            }
            set {
                this.equiposPartido10Field = value;
            }
        }
        
        /// <remarks/>
        public string EquiposPartido11 {
            get {
                return this.equiposPartido11Field;
            }
            set {
                this.equiposPartido11Field = value;
            }
        }
        
        /// <remarks/>
        public string EquiposPartido12 {
            get {
                return this.equiposPartido12Field;
            }
            set {
                this.equiposPartido12Field = value;
            }
        }
        
        /// <remarks/>
        public string EquiposPartido13 {
            get {
                return this.equiposPartido13Field;
            }
            set {
                this.equiposPartido13Field = value;
            }
        }
        
        /// <remarks/>
        public string EquiposPartido14 {
            get {
                return this.equiposPartido14Field;
            }
            set {
                this.equiposPartido14Field = value;
            }
        }
        
        /// <remarks/>
        public string EquiposPartido15 {
            get {
                return this.equiposPartido15Field;
            }
            set {
                this.equiposPartido15Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NotificacionFree1x2 {
        
        private string contenidoField;
        
        private string tituloField;
        
        private string remitenteField;
        
        private System.DateTime fechaCaducidadField;
        
        private System.DateTime fechaCreacionField;
        
        private int idNotificacionField;
        
        private bool leidaField;
        
        private bool borradaField;
        
        /// <remarks/>
        public string Contenido {
            get {
                return this.contenidoField;
            }
            set {
                this.contenidoField = value;
            }
        }
        
        /// <remarks/>
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <remarks/>
        public string Remitente {
            get {
                return this.remitenteField;
            }
            set {
                this.remitenteField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaCaducidad {
            get {
                return this.fechaCaducidadField;
            }
            set {
                this.fechaCaducidadField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
            }
        }
        
        /// <remarks/>
        public int IdNotificacion {
            get {
                return this.idNotificacionField;
            }
            set {
                this.idNotificacionField = value;
            }
        }
        
        /// <remarks/>
        public bool Leida {
            get {
                return this.leidaField;
            }
            set {
                this.leidaField = value;
            }
        }
        
        /// <remarks/>
        public bool Borrada {
            get {
                return this.borradaField;
            }
            set {
                this.borradaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void UltimaVersionFree1X2CompletedEventHandler(object sender, UltimaVersionFree1X2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UltimaVersionFree1X2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UltimaVersionFree1X2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ObtenerBoletoCompletedEventHandler(object sender, ObtenerBoletoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerBoletoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerBoletoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void AlmacenarInformeErrorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ObtenerJornadaActualCompletedEventHandler(object sender, ObtenerJornadaActualCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerJornadaActualCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerJornadaActualCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public JornadaActual Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((JornadaActual)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ObtenerNotificacionesCompletedEventHandler(object sender, ObtenerNotificacionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerNotificacionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerNotificacionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NotificacionFree1x2[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NotificacionFree1x2[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591